_target_: src.datasets.modalities.trajectory_dataset.TrajectoryDataset

name: rot6d
set_name: mixed
dataset_dir: ${dataset.dataset_dir}
num_feats: 9
num_rawfeats: ${dataset.num_rawfeats}
num_cams: ${dataset.num_cams}
standardize: true
standardization: ${dataset.standardization}
